/* ============================================================
   LEXIQUE — glossaire technique (dev, app, site web, SEO)
   Page SEO : ~100 termes définis. FR (marché principal Luxembourg).
   ============================================================ */
export const LEXIQUE = {
  tag: "Lexique",
  title: "LEXIQUE DU WEB, DU DÉVELOPPEMENT & DES APPS",
  intro: "Développement, création de site, application mobile, SEO : une centaine de termes techniques expliqués simplement. Un repère clair pour parler le même langage que votre agence — et faire les bons choix pour votre projet digital.",
  searchPlaceholder: "Rechercher un terme…",
  groups: [
    { cat: "Développement & technique", items: [
      { t:"API", d:"Interface qui permet à deux logiciels de communiquer et d'échanger des données entre eux." },
      { t:"API REST", d:"Style d'API standardisé qui s'appuie sur les requêtes HTTP pour lire et modifier des données." },
      { t:"GraphQL", d:"Langage de requête d'API où le client demande exactement les données dont il a besoin." },
      { t:"Back-end", d:"Partie invisible d'une application : serveur, base de données et logique métier." },
      { t:"Front-end", d:"Partie visible d'un site ou d'une app, avec laquelle l'utilisateur interagit." },
      { t:"Framework", d:"Cadre de développement qui fournit structure et outils prêts à l'emploi (React, Vue…)." },
      { t:"Bibliothèque", d:"Ensemble de fonctions réutilisables qu'un développeur intègre à son projet." },
      { t:"SDK", d:"Kit de développement fourni par une plateforme pour créer des applications compatibles." },
      { t:"Base de données", d:"Système qui stocke, organise et permet de retrouver des données de façon structurée." },
      { t:"SQL", d:"Langage standard pour interroger et manipuler des bases de données relationnelles." },
      { t:"NoSQL", d:"Bases de données non relationnelles, adaptées aux données flexibles et volumineuses." },
      { t:"JSON", d:"Format léger d'échange de données, lisible par l'humain comme par la machine." },
      { t:"Webhook", d:"Notification automatique envoyée d'un service à un autre quand un événement survient." },
      { t:"Git", d:"Système de gestion de versions qui suit l'historique des modifications d'un code." },
      { t:"Dépôt (repository)", d:"Espace où est stocké le code d'un projet, avec son historique complet." },
      { t:"CI/CD", d:"Automatisation des tests et du déploiement du code pour livrer plus vite et plus sûr." },
      { t:"Déploiement", d:"Mise en ligne d'une application ou d'une nouvelle version sur un serveur." },
      { t:"Serveur", d:"Machine qui héberge un site ou une app et répond aux requêtes des utilisateurs." },
      { t:"Cloud", d:"Ressources informatiques (serveurs, stockage) fournies à la demande via internet." },
      { t:"Conteneur (Docker)", d:"Environnement isolé qui embarque une application et tout ce qu'il lui faut pour tourner." },
      { t:"Microservices", d:"Architecture qui découpe une application en petits services indépendants." },
      { t:"Cache", d:"Stockage temporaire de données pour accélérer les accès répétés." },
      { t:"Scalabilité", d:"Capacité d'un système à encaisser une hausse de charge sans perdre en performance." },
      { t:"Refactoring", d:"Réécriture du code pour l'améliorer sans changer son comportement." },
      { t:"Débogage (debug)", d:"Recherche et correction des erreurs (bugs) dans un programme." },
      { t:"Authentification", d:"Vérification de l'identité d'un utilisateur (login, mot de passe, 2FA)." },
      { t:"Token", d:"Jeton sécurisé qui prouve l'identité ou les droits d'un utilisateur lors des échanges." },
      { t:"Chiffrement", d:"Transformation de données en code illisible pour les protéger." },
      { t:"HTTPS / SSL", d:"Protocole et certificat qui sécurisent les échanges entre un navigateur et un site." },
      { t:"Tests unitaires", d:"Tests automatisés qui vérifient qu'une petite partie du code fonctionne correctement." },
    ]},
    { cat: "Création de site web", items: [
      { t:"HTML", d:"Langage de balisage qui structure le contenu d'une page web." },
      { t:"CSS", d:"Langage qui met en forme et stylise une page web (couleurs, mise en page…)." },
      { t:"JavaScript", d:"Langage de programmation qui rend les pages web interactives et dynamiques." },
      { t:"Responsive", d:"Site qui s'adapte automatiquement à toutes les tailles d'écran." },
      { t:"Mobile-first", d:"Approche de conception qui part du mobile avant d'élargir au bureau." },
      { t:"DOM", d:"Représentation en arborescence d'une page, que le navigateur manipule pour l'afficher." },
      { t:"SSR (rendu serveur)", d:"Génération des pages sur le serveur pour un affichage rapide et un meilleur SEO." },
      { t:"CSR (rendu client)", d:"Génération des pages directement dans le navigateur via JavaScript." },
      { t:"SSG", d:"Génération des pages à l'avance, en fichiers statiques ultra-rapides." },
      { t:"PWA", d:"Application web installable qui se comporte comme une app native." },
      { t:"CMS", d:"Système pour gérer le contenu d'un site sans coder (WordPress…)." },
      { t:"Headless CMS", d:"CMS qui gère le contenu via une API, sans imposer l'affichage." },
      { t:"Landing page", d:"Page unique conçue pour convertir un visiteur en prospect ou client." },
      { t:"Wireframe", d:"Schéma fonctionnel d'une page, sans design, pour poser la structure." },
      { t:"Maquette", d:"Représentation visuelle fidèle d'une interface avant développement." },
      { t:"UX", d:"Expérience utilisateur : facilité, clarté et plaisir d'utilisation d'un produit." },
      { t:"UI", d:"Interface utilisateur : apparence et éléments visuels avec lesquels on interagit." },
      { t:"Design system", d:"Bibliothèque de composants et de règles pour un design cohérent." },
      { t:"Accessibilité (a11y)", d:"Conception d'un site utilisable par tous, y compris les personnes handicapées." },
      { t:"WCAG", d:"Normes internationales de référence pour l'accessibilité web." },
      { t:"Nom de domaine", d:"Adresse d'un site sur internet (ex. webgrowth.lu)." },
      { t:"Hébergement", d:"Service qui stocke les fichiers d'un site et le rend accessible en ligne." },
      { t:"DNS", d:"Annuaire qui traduit un nom de domaine en adresse de serveur." },
      { t:"CDN", d:"Réseau de serveurs répartis qui accélère la diffusion des contenus dans le monde." },
      { t:"Certificat SSL", d:"Certificat qui active le HTTPS et sécurise un site (le cadenas)." },
      { t:"Favicon", d:"Petite icône d'un site affichée dans l'onglet du navigateur." },
      { t:"Balise meta", d:"Information invisible dans le code d'une page, utile au SEO et au partage." },
      { t:"Cookie", d:"Petit fichier stocké par le navigateur pour mémoriser des informations." },
      { t:"RGPD", d:"Règlement européen sur la protection des données personnelles." },
      { t:"CTA (appel à l'action)", d:"Bouton ou lien qui incite l'utilisateur à agir (contacter, acheter…)." },
      { t:"Tunnel de conversion", d:"Parcours suivi par un visiteur jusqu'à l'action finale (achat, devis)." },
      { t:"A/B testing", d:"Test comparant deux versions d'une page pour garder la plus performante." },
      { t:"Lazy loading", d:"Chargement différé des images et contenus pour accélérer l'affichage." },
      { t:"Core Web Vitals", d:"Indicateurs de Google mesurant vitesse, réactivité et stabilité d'une page." },
    ]},
    { cat: "Application mobile", items: [
      { t:"Application native", d:"App développée spécifiquement pour iOS ou Android, très performante." },
      { t:"Cross-platform", d:"Une seule base de code pour iOS et Android à la fois." },
      { t:"React Native", d:"Framework pour créer des apps mobiles cross-platform en JavaScript." },
      { t:"Flutter", d:"Framework de Google pour créer des apps cross-platform performantes." },
      { t:"Swift", d:"Langage d'Apple pour développer des applications iOS natives." },
      { t:"Kotlin", d:"Langage moderne pour développer des applications Android natives." },
      { t:"App Store", d:"Boutique d'applications d'Apple pour les appareils iOS." },
      { t:"Google Play", d:"Boutique d'applications de Google pour les appareils Android." },
      { t:"Notification push", d:"Message envoyé sur le téléphone même quand l'app est fermée." },
      { t:"Mode hors ligne", d:"Fonctionnement d'une application sans connexion internet." },
      { t:"Deep link", d:"Lien qui ouvre directement une page précise dans une application." },
      { t:"Splash screen", d:"Écran d'accueil affiché au démarrage d'une application." },
      { t:"Onboarding", d:"Écrans qui guident l'utilisateur lors de sa première utilisation." },
      { t:"ASO", d:"Optimisation d'une fiche d'app pour la rendre plus visible sur les stores." },
      { t:"Build", d:"Version compilée d'une application, prête à être testée ou publiée." },
      { t:"Bêta-test", d:"Phase de test d'une app auprès d'utilisateurs avant sa sortie officielle." },
      { t:"TestFlight", d:"Outil d'Apple pour distribuer une app en test avant publication." },
      { t:"API mobile", d:"Interface qui connecte l'application à un serveur et à ses données." },
    ]},
    { cat: "SEO & performance", items: [
      { t:"SEO", d:"Ensemble des techniques pour améliorer la visibilité d'un site sur les moteurs de recherche." },
      { t:"Référencement naturel", d:"Positionnement gratuit d'un site dans les résultats de recherche." },
      { t:"SEO technique", d:"Optimisation du code, de la vitesse et de la structure pour faciliter l'indexation." },
      { t:"SEO local", d:"Optimisation pour apparaître dans les recherches géolocalisées (« agence web Luxembourg »)." },
      { t:"SEO on-page", d:"Optimisation du contenu et du code d'une page (titres, balises, mots-clés)." },
      { t:"SEO off-page", d:"Actions externes au site, surtout l'obtention de liens entrants." },
      { t:"Backlink", d:"Lien d'un autre site vers le vôtre, gage de confiance pour Google." },
      { t:"Maillage interne", d:"Liens entre les pages d'un même site pour guider visiteurs et robots." },
      { t:"Mot-clé", d:"Terme tapé par les internautes que l'on cible pour être trouvé." },
      { t:"Longue traîne", d:"Requêtes précises et peu concurrentielles, souvent très qualifiées." },
      { t:"SERP", d:"Page de résultats affichée par un moteur de recherche." },
      { t:"Balise title", d:"Titre d'une page affiché dans les résultats de recherche et l'onglet." },
      { t:"Meta description", d:"Court résumé d'une page affiché sous le titre dans les résultats." },
      { t:"Données structurées", d:"Balises (schema.org) qui aident Google à comprendre le contenu d'une page." },
      { t:"Rich snippet", d:"Résultat enrichi (étoiles, prix, FAQ) qui ressort dans la SERP." },
      { t:"Indexation", d:"Ajout d'une page à la base de données d'un moteur de recherche." },
      { t:"Crawl", d:"Exploration d'un site par les robots des moteurs de recherche." },
      { t:"Redirection 301", d:"Redirection permanente d'une ancienne URL vers une nouvelle, sans perte de SEO." },
      { t:"Balise canonical", d:"Indique à Google la version principale d'une page pour éviter les doublons." },
      { t:"GEO", d:"Optimisation pour être cité par les IA génératives (ChatGPT, Perplexity…)." },
      { t:"Featured snippet", d:"Réponse mise en avant tout en haut des résultats Google." },
      { t:"Sitemap", d:"Fichier qui liste les pages d'un site pour aider les moteurs à les explorer." },
    ]},
  ],
};
